# Generated by Django 2.2.5 on 2020-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='difficulty',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], max_length=60),
        ),
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(choices=[('Iowa', 'Iowa'), ('Utah', 'Utah'), ('Rhode Island', 'Rhode Island'), ('Wyoming', 'Wyoming'), ('New Mexico', 'New Mexico'), ('Texas', 'Texas'), ('Arkansas', 'Arkansas'), ('Alabama', 'Alabama'), ('Washington', 'Washington'), ('Ohio', 'Ohio'), ('Tennessee', 'Tennessee'), ('Georgia', 'Georgia'), ('Maryland', 'Maryland'), ('California', 'California'), ('Connecticut', 'Connecticut'), ('Virgina', 'Virgina'), ('North Dakota', 'North Dakota'), ('South Carolina', 'South Carolina'), ('Colorado', 'Colorado'), ('Montana', 'Montana'), ('South Dakota', 'South Dakota'), ('Illinois', 'Illinois'), ('Kentucky', 'Kentucky'), ('Florida', 'Florida'), ('Maine', 'Maine'), ('Minnesota', 'Minnesota'), ('Idaho', 'Idaho'), ('West Virginia', 'West Virginia'), ('Oklahoma', 'Oklahoma'), ('Nebraska', 'Nebraska'), ('Arizona', 'Arizona'), ('Pennsylvania', 'Pennsylvania'), ('Wisconsin', 'Wisconsin'), ('Louisiana', 'Louisiana'), ('Oregon', 'Oregon'), ('Massachusetts', 'Massachusetts'), ('Delaware', 'Delaware'), ('New Hampshire', 'New Hampshire'), ('Michigan', 'Michigan'), ('Mississippi', 'Mississippi'), ('Indiana', 'Indiana'), ('New Jersey', 'New Jersey'), ('Vermont', 'Vermont'), ('Nevada', 'Nevada'), ('Alaska', 'Alaska'), ('Missouri', 'Missouri'), ('Hawaii', 'Hawaii'), ('North Carolina', 'North Carolina'), ('Kansas', 'Kansas'), ('New York', 'New York')], max_length=60),
        ),
    ]
