# Generated by Django 2.2.5 on 2020-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0002_auto_20201215_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(choices=[('New Hampshire', 'New Hampshire'), ('Oregon', 'Oregon'), ('Kansas', 'Kansas'), ('Vermont', 'Vermont'), ('Alabama', 'Alabama'), ('Minnesota', 'Minnesota'), ('Maine', 'Maine'), ('Montana', 'Montana'), ('Colorado', 'Colorado'), ('New Jersey', 'New Jersey'), ('Washington', 'Washington'), ('New York', 'New York'), ('Tennessee', 'Tennessee'), ('Maryland', 'Maryland'), ('Wisconsin', 'Wisconsin'), ('North Dakota', 'North Dakota'), ('West Virginia', 'West Virginia'), ('Mississippi', 'Mississippi'), ('Texas', 'Texas'), ('Michigan', 'Michigan'), ('Pennsylvania', 'Pennsylvania'), ('Oklahoma', 'Oklahoma'), ('Arkansas', 'Arkansas'), ('South Dakota', 'South Dakota'), ('Massachusetts', 'Massachusetts'), ('New Mexico', 'New Mexico'), ('Hawaii', 'Hawaii'), ('Alaska', 'Alaska'), ('Nebraska', 'Nebraska'), ('Idaho', 'Idaho'), ('Rhode Island', 'Rhode Island'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Virgina', 'Virgina'), ('Louisiana', 'Louisiana'), ('Missouri', 'Missouri'), ('Arizona', 'Arizona'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('North Carolina', 'North Carolina'), ('California', 'California'), ('Ohio', 'Ohio'), ('Nevada', 'Nevada'), ('South Carolina', 'South Carolina'), ('Utah', 'Utah'), ('Wyoming', 'Wyoming'), ('Georgia', 'Georgia'), ('Florida', 'Florida'), ('Illinois', 'Illinois'), ('Kentucky', 'Kentucky')], max_length=60),
        ),
    ]
