# Generated by Django 2.2.5 on 2020-12-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0004_auto_20201215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='trails',
            name='image',
            field=models.URLField(),
        ),
    ]
