# Generated by Django 2.2.5 on 2020-12-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0005_auto_20201215_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trails',
            name='length',
        ),
        migrations.AddField(
            model_name='trails',
            name='miles',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='trails',
            name='camping',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='trails',
            name='image',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
