# Generated by Django 2.2.5 on 2020-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0006_auto_20201215_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
