# Generated by Django 2.2.5 on 2020-12-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingApp', '0008_auto_20201218_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
