# Generated by Django 4.0.4 on 2022-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('peopling', 'peopling'), ('adulting', 'adulting'), ('crisis', 'crisis')], max_length=30)),
                ('Numb', models.IntegerField(default=0, max_length=3)),
                ('Instr', models.CharField(blank=True, default='', max_length=30)),
                ('Durat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
