# Generated by Django 4.0.4 on 2022-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Numb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('crisis', 'crisis'), ('peopling', 'peopling'), ('adulting', 'adulting')], max_length=30),
        ),
    ]
