# Generated by Django 4.0.4 on 2022-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0002_alter_djangoclasses_numb_alter_djangoclasses_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='Numb',
            new_name='CourseNum',
        ),
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='Durat',
            new_name='Duration',
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('crisis', 'crisis'), ('adulting', 'adulting'), ('peopling', 'peopling')], max_length=30),
        ),
    ]
