# Generated by Django 4.0.4 on 2022-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0003_rename_numb_djangoclasses_coursenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('peopling', 'peopling'), ('crisis', 'crisis'), ('adulting', 'adulting')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('peopling', 'peopling'), ('crisis', 'crisis'), ('adulting', 'adulting')], max_length=30)),
                ('CourseNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('peopling', 'peopling'), ('crisis', 'crisis'), ('adulting', 'adulting')], max_length=30),
        ),
    ]
