# Generated by Django 4.0.4 on 2022-05-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0004_book_prereq_alter_djangoclasses_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='prereq',
        ),
    ]
