# Generated by Django 4.0.4 on 2022-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0005_delete_book_delete_prereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='CourseNum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
