# Generated by Django 4.0.4 on 2022-05-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheClassApp', '0006_alter_djangoclasses_coursenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('crisis', 'crisis'), ('adulting', 'adulting'), ('peopling', 'peopling')], max_length=30),
        ),
    ]
