# Generated by Django 2.2.5 on 2021-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YTname', models.CharField(max_length=100)),
                ('YTlink', models.CharField(max_length=100)),
            ],
        ),
    ]
