# Generated by Django 2.2.5 on 2021-04-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnimeName', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('Review', models.TextField(max_length=500)),
            ],
        ),
    ]
