# Generated by Django 2.2.5 on 2021-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=2),
        ),
    ]
