# Generated by Django 2.2.5 on 2021-04-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0003_auto_20210422_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.CharField(choices=[('Rating of 1', ' Rating of 1'), ('Rating of 2', 'Rating of 2'), ('Rating of 3', ' Rating of 3'), ('Rating of 4', 'Rating of 4'), ('Rating of 5', 'Rating of 5')], default=5, max_length=20),
        ),
    ]
