# Generated by Django 2.2.5 on 2021-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0004_auto_20210422_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.CharField(choices=[('1 star', '1 star'), ('2 stars', '2 stars'), ('3 stars', '3 stars'), ('4 stars', '4 stars'), ('5 stars', '5 stars'), ('6 stars', '6 stars'), ('7 stars', '7 stars'), ('8 stars', '8 stars'), ('9 stars', '9 stars'), ('10 stars', '10 stars')], default=10, max_length=20),
        ),
    ]
