# Generated by Django 2.2.5 on 2021-04-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0005_auto_20210422_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.CharField(choices=[('1 Star', '1 Star'), ('2 Stars', '2 Stars'), ('3 Stars', '3 Stars'), ('4 Stars', '4 Stars'), ('5 Stars', '5 Stars'), ('6 Stars', '6 Stars'), ('7 Stars', '7 Stars'), ('8 Stars', '8 Stars'), ('9 Stars', '9 Stars'), ('10 Stars', '10 Stars')], default=10, max_length=20),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=20)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAnimeApp.Review')),
            ],
        ),
    ]
