# Generated by Django 2.2.5 on 2021-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0006_auto_20210422_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Rating',
            field=models.CharField(max_length=20),
        ),
    ]
