# Generated by Django 2.2.5 on 2021-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0007_auto_20210422_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='About',
            field=models.TextField(default='about', max_length=500),
        ),
    ]
