# Generated by Django 2.2.5 on 2021-04-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheAnimeApp', '0008_review_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
