# Generated by Django 2.2.5 on 2021-06-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(max_length=60)),
                ('AlbumName', models.CharField(blank=True, max_length=60)),
                ('ReleaseYear', models.IntegerField(blank=True, max_length=4)),
                ('AlbumGenre', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
