# Generated by Django 2.2.5 on 2021-06-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HipHopReviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='AlbumGenre',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='ReleaseYear',
            field=models.IntegerField(blank=True),
        ),
    ]
