# Generated by Django 2.2.5 on 2021-03-22 21:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_budget', models.IntegerField()),
            ],
            managers=[
                ('account', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(default='Expense Name', max_length=30)),
                ('cost', models.FloatField()),
                ('date_added', models.DateTimeField()),
                ('username', models.CharField(default='Your Name!', max_length=20)),
            ],
        ),
    ]
