# Generated by Django 2.2.5 on 2021-03-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
