# Generated by Django 2.2.5 on 2021-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0002_delete_accountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetinfo',
            name='details',
            field=models.TextField(default='Details...', max_length=300),
        ),
        migrations.AlterField(
            model_name='budgetinfo',
            name='date_added',
            field=models.DateField(),
        ),
    ]
