# Generated by Django 2.2.5 on 2021-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_type', models.CharField(choices=[('VEGAN', 'vegan'), ('PESCATARIAN', 'pescatarian'), ('CARNIVORE', 'carnivore'), ('SALAD', 'salad'), ('SOUP', 'soup')], max_length=30)),
                ('recipe_name', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=300)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
