# Generated by Django 2.2.5 on 2021-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldRecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(max_length=30),
        ),
    ]
