# Generated by Django 2.2.5 on 2021-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmName', models.CharField(max_length=100)),
                ('ReleaseYear', models.IntegerField(blank=True)),
                ('StarNames', models.CharField(blank=True, max_length=100)),
                ('DirectorName', models.CharField(blank=True, max_length=60)),
                ('MovieSummary', models.TextField(blank=True)),
            ],
        ),
    ]
