# Generated by Django 2.2.5 on 2021-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RidleyVerse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YTname', models.CharField(max_length=100)),
                ('YTlink', models.CharField(max_length=100)),
            ],
        ),
    ]
