# Generated by Django 2.2.5 on 2021-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('use', models.CharField(choices=[('Handling', 'Handling'), ('Shaping', 'Shaping'), ('Removing Material', 'Removing Material'), ('Not Part of the Tang', 'Not Part of the Tang'), ('Other (Please specify in description)', 'Other (Please specify in description)')], max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('link', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
    ]
