# Generated by Django 2.2.5 on 2021-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blacksmithing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='tool',
            name='link',
            field=models.TextField(max_length=600),
        ),
    ]
