# Generated by Django 2.2.5 on 2021-04-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sharks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('location', models.CharField(choices=[('Atlantic', 'Atlantic'), ('Indian', 'Indian'), ('Pacific', 'Pacific'), ('Artic', 'Artic')], max_length=50)),
                ('endangered', models.CharField(max_length=50)),
            ],
        ),
    ]
