# Generated by Django 2.2.5 on 2021-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('Year', models.IntegerField(default='')),
            ],
        ),
    ]
