# Generated by Django 2.2.5 on 2021-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Northwest', 'Northwest'), ('North', 'North'), ('Northeast', 'Northeast'), ('Southeast', 'Southeast'), ('Southwest', 'Southwest'), ('Beaverton', 'Beaverton'), ('Hillsboro', 'Hillsboro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='commute',
            field=models.CharField(choices=[('Long', 'Long'), ('Fair', 'Fair'), ('Short', 'Short')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_life_stage',
            field=models.CharField(choices=[('Family', 'Family'), ('Young Professional', 'Young Professional'), ('Retiree', 'Retiree')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='walkability',
            field=models.CharField(choices=[('Very Walkable', 'Very Walkable'), ('Somewhat Walkable', 'Somewhat Walkable'), ('Not Walkable', 'Not Walkable')], max_length=40),
        ),
    ]
