# Generated by Django 2.2.5 on 2021-08-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeighborhoodReview', '0002_auto_20210730_1031'),
        ('NeighborhoodReview', '0002_auto_20210729_1317'),
    ]

    operations = [
    ]
