# Generated by Django 2.2.5 on 2021-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0002_auto_20210114_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednbagame',
            name='game_notes',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='favplayer',
            name='corresponding_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Chicago Bulls', 'Chicago Bulls'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Denver Nuggets', 'Denver Nuggets'), ('Detroit Pistons', 'Detroit Pistons'), ('Golden State Warriors', 'Golden State Warriors'), ('Houston Rockets', 'Houston Rockets'), ('Indiana Pacers', 'Indiana Pacers'), ('Los Angeles Clippers', 'Los Angeles Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Miami Heat', 'Miami Heat'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('Minnesota Timberwolves', 'Minnesota Timberwolves'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('New York Knicks', 'New York Knicks'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Orlando Magic', 'Orlando Magic'), ('Philadelphia 76ers', 'Philadelphia 76ers'), ('Phoenix Suns', 'Phoenix Suns'), ('Portland Trailblazers', 'Portland Trailblazers'), ('Sacramento Kings', 'Sacramento Kings'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Toronto Raptors', 'Toronto Raptors'), ('Utah Jazz', 'Utah Jazz'), ('Washington Wizards', 'Washington Wizards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savednbagame',
            name='away_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Chicago Bulls', 'Chicago Bulls'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Denver Nuggets', 'Denver Nuggets'), ('Detroit Pistons', 'Detroit Pistons'), ('Golden State Warriors', 'Golden State Warriors'), ('Houston Rockets', 'Houston Rockets'), ('Indiana Pacers', 'Indiana Pacers'), ('Los Angeles Clippers', 'Los Angeles Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Miami Heat', 'Miami Heat'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('Minnesota Timberwolves', 'Minnesota Timberwolves'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('New York Knicks', 'New York Knicks'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Orlando Magic', 'Orlando Magic'), ('Philadelphia 76ers', 'Philadelphia 76ers'), ('Phoenix Suns', 'Phoenix Suns'), ('Portland Trailblazers', 'Portland Trailblazers'), ('Sacramento Kings', 'Sacramento Kings'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Toronto Raptors', 'Toronto Raptors'), ('Utah Jazz', 'Utah Jazz'), ('Washington Wizards', 'Washington Wizards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savednbagame',
            name='home_team',
            field=models.CharField(choices=[('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Chicago Bulls', 'Chicago Bulls'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Denver Nuggets', 'Denver Nuggets'), ('Detroit Pistons', 'Detroit Pistons'), ('Golden State Warriors', 'Golden State Warriors'), ('Houston Rockets', 'Houston Rockets'), ('Indiana Pacers', 'Indiana Pacers'), ('Los Angeles Clippers', 'Los Angeles Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Miami Heat', 'Miami Heat'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('Minnesota Timberwolves', 'Minnesota Timberwolves'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('New York Knicks', 'New York Knicks'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Orlando Magic', 'Orlando Magic'), ('Philadelphia 76ers', 'Philadelphia 76ers'), ('Phoenix Suns', 'Phoenix Suns'), ('Portland Trailblazers', 'Portland Trailblazers'), ('Sacramento Kings', 'Sacramento Kings'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Toronto Raptors', 'Toronto Raptors'), ('Utah Jazz', 'Utah Jazz'), ('Washington Wizards', 'Washington Wizards')], max_length=50),
        ),
    ]
