# Generated by Django 2.2.5 on 2020-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindPetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablepet',
            name='age',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
