# Generated by Django 2.2.5 on 2021-10-12 20:46
# Generated by Django 2.2.5 on 2021-10-13 00:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=50)),
                ('Points_Per_Game', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Rebounds_Per_Game', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Assists_Per_Game', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Steals_Per_Game', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            managers=[
                ('Players', django.db.models.manager.Manager()),
            ],
        ),
    ]
