# Generated by Django 2.2.5 on 2021-01-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue')], default='Select Mood', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
