# Generated by Django 2.2.5 on 2021-01-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0002_auto_20210120_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue')], default='Select Mood', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='color',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_name',
        ),
    ]
