# Generated by Django 2.2.5 on 2021-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0003_auto_20210120_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry2',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AddField(
            model_name='entry',
            name='Activities',
            field=models.CharField(choices=[('Working', 'Working'), ('With Friends', 'With Friends'), ('Hobbies', 'Hobbies'), ('Running Errands', 'Running Errands'), ('Sports', 'Sports')], default='Select Mood', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='Hours_Slept',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='Mood',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Good', 'Good'), ('Meh', 'Meh'), ('Down', 'Down'), ('Awful', 'Awful')], default='Select Mood', max_length=50),
        ),
    ]
