# Generated by Django 2.2.5 on 2021-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0005_auto_20210122_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='Author',
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
