# Generated by Django 2.2.5 on 2021-01-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0006_auto_20210122_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='Activities',
            field=models.CharField(choices=[('Working', 'Working'), ('With Friends', 'With Friends'), ('Hobbies', 'Hobbies'), ('Running Errands', 'Running Errands'), ('Sports', 'Sports')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='Mood',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Good', 'Good'), ('Meh', 'Meh'), ('Down', 'Down'), ('Awful', 'Awful')], default='', max_length=50),
        ),
    ]
