# Generated by Django 2.2.5 on 2021-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0011_auto_20210122_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Hours_Slept',
            field=models.CharField(choices=[(1, '0-4 Hours'), (2, '5-6 Hours'), (3, '7-8 Hours'), (4, '9-10 Hours'), (5, '11-24 Hours')], default='Select State', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Mood',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Good', 'Good'), ('Meh', 'Meh'), ('Down', 'Down'), ('Awful', 'Awful')], default='Select State', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
