# Generated by Django 2.2.5 on 2021-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReflectiveJournal', '0012_auto_20210122_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Hours_Slept',
            field=models.CharField(choices=[('0-4 Hours', '0-4 Hours'), ('5-6 Hours', '5-6 Hours'), ('7-8 Hours', '7-8 Hours'), ('9-10 Hours', '9-10 Hours'), ('11-24 Hours', '11-24 Hours')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='Mood',
            field=models.CharField(choices=[('Awesome', 'Awesome'), ('Good', 'Good'), ('Meh', 'Meh'), ('Down', 'Down'), ('Awful', 'Awful')], default='', max_length=50, null=True),
        ),
    ]
