# Generated by Django 2.2.5 on 2021-05-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0004_auto_20210524_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='fName',
            new_name='first_name',
        ),
    ]
