# Generated by Django 2.2.5 on 2021-05-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0006_auto_20210524_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
    ]
