# Generated by Django 2.2.5 on 2021-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0007_remove_resource_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
