# Generated by Django 2.2.5 on 2021-05-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0009_auto_20210526_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
