# Generated by Django 2.2.5 on 2021-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RockLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('address', models.CharField(blank=True, default='', max_length=60)),
                ('location_description', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
