# Generated by Django 2.2.5 on 2021-04-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
            ],
        ),
    ]
