# Generated by Django 2.2.5 on 2021-05-25 11:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=40)),
                ('L_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=60)),
                ('Art_type', models.CharField(choices=[('T', 'Traditional'), ('O', 'Oil'), ('W', 'Watercolor'), ('D', 'Digital'), ('A', 'Acrylic'), ('P', 'Pottery'), ('S', 'Sculpture')], max_length=1)),
                ('Picture', models.URLField()),
            ],
            managers=[
                ('Artists', django.db.models.manager.Manager()),
            ],
        ),
    ]
