# Generated by Django 2.2.5 on 2021-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Art_type',
            new_name='Art_Type',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='F_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='L_name',
            new_name='Last_Name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='Email',
            field=models.CharField(help_text='Please make sure your email is correct!', max_length=60),
        ),
    ]
