# Generated by Django 2.2.5 on 2021-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Year',
            field=models.IntegerField(default=''),
        ),
    ]
