# Generated by Django 2.2.5 on 2021-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='sowtime',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='planner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='planner',
            name='zone',
            field=models.CharField(max_length=30),
        ),
    ]
