# Generated by Django 2.2.5 on 2021-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0002_auto_20210316_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='zone',
            new_name='Growing_Zone',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sowtime',
            new_name='Harvest_Time_Frame',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='name',
            new_name='Vegetable_Name',
        ),
        migrations.AddField(
            model_name='planner',
            name='Sowing_Time_Frame',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterModelTable(
            name='planner',
            table='planner',
        ),
    ]
