# Generated by Django 2.2.5 on 2021-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0004_auto_20210316_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='Harvest_Notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
