# Generated by Django 2.2.5 on 2021-03-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0005_auto_20210316_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planner',
            table='Garden Planner',
        ),
    ]
