# Generated by Django 2.2.5 on 2021-03-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0006_auto_20210316_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='Growing_Year',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='planner',
            name='General_Care_Notes',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='Growing_Zone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='planner',
            name='Harvest_Notes',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='Vegetable_Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='planner',
            table='Garden_Planner',
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Growing_Season_Observations', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('Harvest_Weight', models.CharField(blank=True, max_length=30)),
                ('Harvest_Observations', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('Vegetable_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenApp.Planner')),
            ],
        ),
    ]
