# Generated by Django 2.2.5 on 2021-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0007_auto_20210317_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='General_Care_Notes',
            new_name='General_Care_Tips',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='Harvest_Notes',
            new_name='Harvest_Tips',
        ),
        migrations.AlterField(
            model_name='eval',
            name='Growing_Season_Observations',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='eval',
            name='Harvest_Observations',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
