# Generated by Django 2.2.5 on 2021-03-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0008_auto_20210319_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eval',
            new_name='Tracker',
        ),
    ]
