# Generated by Django 2.2.5 on 2021-03-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenApp', '0009_auto_20210323_0816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tracker',
            table='Garden_Tracker',
        ),
    ]
