# Generated by Django 2.2.5 on 2021-02-22 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor_name', models.CharField(max_length=25)),
            ],
            managers=[
                ('conductors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=50)),
                ('piece_composer', models.CharField(max_length=25)),
            ],
            managers=[
                ('pieces', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orchestra_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('artistic_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpcomingConcertsApp.Conductor')),
            ],
            managers=[
                ('orchestras', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpcomingConcertsApp.Conductor')),
                ('orchestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpcomingConcertsApp.Orchestra')),
                ('pieces', models.ManyToManyField(to='UpcomingConcertsApp.Piece')),
            ],
            managers=[
                ('concerts', django.db.models.manager.Manager()),
            ],
        ),
    ]
