# Generated by Django 2.2.5 on 2021-06-01 19:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('nu-metal', 'nu-metal'), ('metalcore', 'metalcore'), ('rock', 'rock'), ('pop', 'pop'), ('classical', 'classical'), ('other', 'other')], max_length=50)),
                ('year', models.IntegerField()),
            ],
            managers=[
                ('Songs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=50)),
                ('playlist_description', models.TextField()),
                ('playlist_songs', models.ManyToManyField(to='ArtistTrack.Song')),
            ],
            managers=[
                ('Playlists', django.db.models.manager.Manager()),
            ],
        ),
    ]
