# Generated by Django 2.2.5 on 2021-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreweriesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBreweries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
