# Generated by Django 2.2.5 on 2021-10-08 01:33
# Generated by Django 2.2.5 on 2021-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Publisher', models.CharField(max_length=50)),
                ('Year', models.IntegerField(default=2021)),
                ('Description', models.TextField(default='Type your review here (optional)')),
                ('Thumbnail', models.CharField(blank=True, max_length=200)),
                ('Image', models.CharField(blank=True, max_length=200)),
                ('Favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-Favorite', 'Name', 'id'),
            },
        ),
    ]
