# Generated by Django 2.2.5 on 2021-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='sets',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='repetitions',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='target_muscle',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms')], max_length=60),
        ),
    ]
