# Generated by Django 2.2.5 on 2021-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Combo', 'Combo'), ('Other', 'Other')], max_length=8)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('website', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
