# Generated by Django 2.2.5 on 2021-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=70)),
                ('Author', models.CharField(default='', max_length=50)),
                ('Series', models.CharField(default='', max_length=50)),
                ('Synopsis', models.TextField(default='', max_length=750)),
                ('Review', models.TextField(default='', max_length=750)),
                ('Rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
        ),
    ]
