# Generated by Django 2.2.5 on 2021-07-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteTaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoteTaking.Categorie'),
        ),
    ]
