# Generated by Django 2.2.5 on 2021-04-06 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.CharField(max_length=60)),
                ('coin_unit', models.CharField(max_length=60)),
                ('chain_type', models.CharField(choices=[('Proof of Work', 'Proof of Work'), ('Proof of Stake', 'Proof of Stake'), ('Other', 'Other')], max_length=200)),
                ('launch_date', models.DateField(default='2021-03-30')),
            ],
            managers=[
                ('Currencies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CoinStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('as_of_date', models.DateField()),
                ('supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transactions_per_sec', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CryptoApp.Currency')),
            ],
            managers=[
                ('CoinStatuses', django.db.models.manager.Manager()),
            ],
        ),
    ]
