# Generated by Django 2.2.5 on 2021-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='description',
            name='first_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='description',
            name='last_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
