# Generated by Django 2.2.5 on 2021-09-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20210908_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
