# Generated by Django 2.2.5 on 2021-03-03 20:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hot drinks', 'hot drinks'), ('cold drinks', 'cold drinks'), ('breakfast', 'breakfast'), ('extras', 'extras')], max_length=60)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
            managers=[
                ('drink', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hot drinks', 'hot drinks'), ('cold drinks', 'cold drinks'), ('breakfast', 'breakfast'), ('extras', 'extras')], max_length=60)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('recipe', models.TextField(max_length=10000)),
                ('duration', models.IntegerField()),
            ],
            managers=[
                ('recipes', django.db.models.manager.Manager()),
            ],
        ),
    ]
