# Generated by Django 2.2.5 on 2021-03-04 21:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='drink',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
