# Generated by Django 2.2.5 on 2020-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='case',
            field=models.CharField(blank='False', choices=[('Prime Keyboards Prime_E', 'Prime Keyboards Prime_E'), ('Funderburker TMOv1', 'Funderburker TMOv1'), ('Mekanisk Klippe', 'Mekanisk Klippe'), ('Rama M60-A', 'Rama M60-A'), ('OLKB Planck', 'OLKB Planck'), ('CannonKeys Savage 65', 'CannonKeys Savage 65'), ('Funderburker TMOv2', 'Funderburker TMOv2'), ('Think 6.5 v1', 'Think 6.5 v1'), ('Mekanisk Fjell', 'Mekanisk Fjell'), ('Project Keyboard Sirius', 'Project Keyboard Sirius'), ('Quantic Kyuu 65%', 'Quantic Kyuu 65%'), ('Percent Studio Canoe Gen2', 'Percent Studio Canoe Gen2'), ('Smith + Rune Iron 165', 'Smith + Rune Iron 165'), ('Demo & Airpotter Arc80 TKL', 'Demo & Airpotter Arc80 TKL'), ('Dixie Mech Bauer', 'Dixie Mech Bauer'), ('OLKB Preonic', 'OLKB Preonic'), ('Noxary XRF', 'Noxary XRF'), ('Keycult No.2 TKL', 'Keycult No.2 TKL'), ('LZ PhysiX', 'LZ PhysiX'), ('Noxary 268.2', 'Noxary 268.2'), ('TGR Jane', 'TGR Jane'), ('Norbauer Norbaforce', 'Norbauer Norbaforce'), ('Exclusive E6.5', 'Exclusive E6.5'), ('Keycult No.2/65', 'Keycult No.2/65'), ('Ai03 Keyboards Polaris', 'Ai03 Keyboards Polaris'), ('Crykyn Dawn 75%', 'Crykyn Dawn 75%'), ('Proto[Typist] J-02', 'Proto[Typist] J-02'), ('Satisfaction 75', 'Satisfaction 75'), ('Norbauer Heavy-9', 'Norbauer Heavy-9'), ('TGR Alice', 'TGR Alice'), ('Dixie Mech Bauer 2', 'Dixie Mech Bauer 2'), ('Mekanisk Tind', 'Mekanisk Tind'), ('Rama Koyu', 'Rama Koyu'), ('CannonKeys Chimera 65', 'CannonKeys Chimera 65'), ('Project Keyboard Kepler FC65', 'Project Keyboard Kepler FC65'), ('TGR Jane v2 CE', 'TGR Jane v2 CE'), ('Keycult No.1 TKL', 'Keycult No.1 TKL'), ('Keycult No.1/65', 'Keycult No.1/65'), ('Zambumon Verne', 'Zambumon Verne'), ('Smith + Rune Iron 180', 'Smith + Rune Iron 180'), ('Satisfaction 75 r2', 'Satisfaction 75 r2'), ('Salamander TKL', 'Salamander TKL'), ('Zambumon Sar', 'Zambumon Sar'), ('Norbauer Heavy-6', 'Norbauer Heavy-6'), ('Norbauer Novatouch', 'Norbauer Novatouch'), ('Keycult No.2 TKL Rev. 1', 'Keycult No.2 TKL Rev. 1'), ('TGR 910', 'TGR 910'), ('Rama Kara', 'Rama Kara'), ('Rama M65-A', 'Rama M65-A'), ('Exclusive E8.5 TKL', 'Exclusive E8.5 TKL'), ('TGR Jane v2', 'TGR Jane v2'), ('Fox Lab Time TKL', 'Fox Lab Time TKL'), ('Think 6.5 v2', 'Think 6.5 v2'), ('Project Keyboard Tengu', 'Project Keyboard Tengu'), ('Proto[Typist] J-01', 'Proto[Typist] J-01'), ('Exclusive E7', 'Exclusive E7'), ('Norbauer Norbaforce Mark II', 'Norbauer Norbaforce Mark II'), ('Percent Studio Canoe', 'Percent Studio Canoe'), ('Rama M65-B', 'Rama M65-B'), ('Exclusive E7-v2', 'Exclusive E7-v2'), ('Project Keyboard Kepler', 'Project Keyboard Kepler'), ('Keycult No.1/60', 'Keycult No.1/60'), ('Keycult No.1 TKL Rev.1', 'Keycult No.1 TKL Rev. 1'), ('Wilba.Tech Thermal', 'Wilba.Tech Thermal'), ('Lin Montage', 'Lin Montage'), ('Rama M60-A SEQ2', 'Rama M60-A SEQ2'), ('Noxary 268', 'Noxary 268'), ('Other', 'Other'), ('Norbauer Heavy Grail', 'Norbauer Grail'), ('The Key Company CandyBar Premium', 'The Key Company CandyBar Premium'), ('Reconsiderit Southpaw 65+', 'Reconsiderit Southpaw 65+'), ('CannonKeys Brutal 60', 'CannonKeys Brutal 60'), ('Xeno', 'Xeno'), ('Rama U80-A SEQ2', 'Rama U80-ASEQ2')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='pcb',
            field=models.CharField(blank='False', choices=[('No PCB(handwired)', 'No PCB(handwired)'), ('Hotswap', 'Hotswap'), ('Solderable', 'Solderable')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='plate',
            field=models.CharField(blank='False', choices=[('Aluminum', 'Aluminum'), ('POM', 'POM'), ('Titanium', 'Titanium'), ('Integrated Half Plate', 'Integrated Half Plate'), ('Acrylic Half Plate', 'Acrylic Half Plate'), ('Brass', 'Brass'), ('Acrylic', 'Acrylic'), ('Polycarbonate Half Plate', 'Polycarbonate Half Plate'), ('POM Half Plate', 'POM Half Plate'), ('Carbon Fiber', 'Carbon Fiber'), ('Integrated', 'Integrated'), ('Carbon Fiber Half Plate', 'Carbon Fiber Half Plate'), ('Brass Half Plate', 'Brass Half Plate'), ('Other', 'Other'), ('None', 'None'), ('Stainless Steel Half Plate', 'Stainless Steel Half Plate'), ('Polycarbonate', 'Polycarbonate'), ('Stainless Steel', 'Stainless Steel'), ('Aluminum Half Plate', 'Aluminum Half Plate'), ('Titanium Half Plate', 'Titanium Half Plate')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='stabilizers',
            field=models.CharField(blank='False', choices=[('Durock Stabilizers', 'Durock Stabilizers'), ('None', 'None'), ('Cherry Stabilizers', 'Cherry Stabilizers'), ('C3 Equalz Stabilizers', 'C3 Equalz Stabilizers'), ('EverGlide Stabilizers', 'EverGlide Stabilizers'), ('Zeal PC Stabilizers', 'Zeal PC Stabilizers'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='switches',
            field=models.CharField(blank='False', choices=[('Zeal Sakurio', 'Zeal Sakurio'), ('Drop Holy Pandas', 'Drop Holy Pandas'), ('Kailh Pro Heavy Plum', 'Kailh Pro Heavy Plum'), ('Kailh Pro Purple', 'Kailh Pro Purple'), ('Kailh Pro Heavy Berry', 'Kailh Pro Heavy Berry'), ('Gateron Clear', 'Gateron Clear'), ('Cherry MX Black', 'Cherry MX Black'), ('Others', 'Others'), ('Kailh Black', 'Kailh Black'), ('Cherry MX Speed Silvers', 'Cherry MX Speed Silvers'), ('Kailh Brown', 'Kailh Brown'), ('Cherry MX Brown', 'Cherry MX Brown'), ('Cherry MX Yellow', 'Cherry MX Yellow'), ('Gateron Silent Red', 'Gateron Silent Red'), ('Cherry MX Silent Red', 'Cherry MX Silent Red'), ('C3 Tangerines', 'C3 Tangerines'), ('Gateron Silent Black', 'Gateron Silent Black'), ('Cherry MX White', 'Cherry MX White'), ('Kailh Box Navy', 'Kailh Box Navy'), ('Gateron Silent Clear', 'Gateron Silent Clear'), ('Gateron Brown', 'Gateron Brown'), ('Gateron Red', 'Gateron Red'), ('Gateron Silent Yellow', 'Gateron Silent Yellow'), ('Cherry MX Red', 'Cherry MX Red'), ('Zeal Healio', 'Zeal Healio'), ('Gateron Inks', 'Gateron Inks'), ('Gateron Blue', 'Gateron Blue'), ('Cherry MX Blue', 'Cherry MX Blue'), ('Zeal Zealio', 'Zeal Zealio'), ('Gateron Silent Brown', 'Gateron Silent Brown'), ('Kailh Pro Heavy Sage', 'Kailh Pro Heavy Sage'), ('Zeal Roselio', 'Zeal Roselio'), ('Gateron Green', 'Gateron Green'), ('Kailh Blue', 'Kailh Blue'), ('Gateron Black', 'Gateron Black'), ('Cherry MX Grey', 'Cherry MX Grey'), ('Cherry MX Silent Black', 'Cherry MX Silent Black'), ('Cherry MX Green', 'Cherry MX Green'), ('Zeal Tealio', 'Zeal Tealio'), ('Kailh Pro Light Green', 'Kailh Pro Light Green'), ('Gateron Yellow', 'Gateron Yellow'), ('Kailh Pro Burgundy', 'Kailh Pro Burgundy'), ('Kailh Red', 'Kailh Red'), ('Zeal Zilent', 'Zeal Zilent'), ('Cherry MX Clear', 'Cherry MX Clear'), ('Gateron Silent Inks', 'Gateron Silent Inks')], default='', max_length=50),
        ),
    ]
