# Generated by Django 2.2.5 on 2020-12-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0002_auto_20201217_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='case',
            field=models.CharField(blank='False', choices=[('Ai03 Keyboards Polaris', 'Ai03 Keyboards Polaris'), ('Demo & Airpotter Arc80 TKL', 'Demo & Airpotter Arc80 TKL'), ('Dixie Mech Bauer', 'Dixie Mech Bauer'), ('Dixie Mech Bauer 2', 'Dixie Mech Bauer 2'), ('CannonKeys Brutal 60', 'CannonKeys Brutal 60'), ('CannonKeys Chimera 65', 'CannonKeys Chimera 65'), ('CannonKeys Savage 65', 'CannonKeys Savage 65'), ('Crykyn Dawn 75%', 'Crykyn Dawn 75%'), ('Exclusive E6.5', 'Exclusive E6.5'), ('Exclusive E7', 'Exclusive E7'), ('Exclusive E7-v2', 'Exclusive E7-v2'), ('Exclusive E8.5 TKL', 'Exclusive E8.5 TKL'), ('Fox Lab Time TKL', 'Fox Lab Time TKL'), ('Funderburker TMOv1', 'Funderburker TMOv1'), ('Funderburker TMOv2', 'Funderburker TMOv2'), ('Keycult No.1/60', 'Keycult No.1/60'), ('Keycult No.1/65', 'Keycult No.1/65'), ('Keycult No.1 TKL', 'Keycult No.1 TKL'), ('Keycult No.1 TKL Rev.1', 'Keycult No.1 TKL Rev. 1'), ('Keycult No.2/65', 'Keycult No.2/65'), ('Keycult No.2 TKL', 'Keycult No.2 TKL'), ('Keycult No.2 TKL Rev. 1', 'Keycult No.2 TKL Rev. 1'), ('Lin Montage', 'Lin Montage'), ('LZ PhysiX', 'LZ PhysiX'), ('Mekanisk Fjell', 'Mekanisk Fjell'), ('Mekanisk Klippe', 'Mekanisk Klippe'), ('Mekanisk Tind', 'Mekanisk Tind'), ('Norbauer Heavy-9', 'Norbauer Heavy-9'), ('Norbauer Heavy-6', 'Norbauer Heavy-6'), ('Norbauer Heavy Grail', 'Norbauer Grail'), ('Norbauer Norbaforce', 'Norbauer Norbaforce'), ('Norbauer Norbaforce Mark II', 'Norbauer Norbaforce Mark II'), ('Norbauer Novatouch', 'Norbauer Novatouch'), ('Noxary 268', 'Noxary 268'), ('Noxary 268.2', 'Noxary 268.2'), ('Noxary XRF', 'Noxary XRF'), ('OLKB Planck', 'OLKB Planck'), ('OLKB Preonic', 'OLKB Preonic'), ('Percent Studio Canoe', 'Percent Studio Canoe'), ('Percent Studio Canoe Gen2', 'Percent Studio Canoe Gen2'), ('Prime Keyboards Prime_E', 'Prime Keyboards Prime_E'), ('Project Keyboard Kepler', 'Project Keyboard Kepler'), ('Project Keyboard Kepler FC65', 'Project Keyboard Kepler FC65'), ('Project Keyboard Sirius', 'Project Keyboard Sirius'), ('Project Keyboard Tengu', 'Project Keyboard Tengu'), ('Proto[Typist] J-01', 'Proto[Typist] J-01'), ('Proto[Typist] J-02', 'Proto[Typist] J-02'), ('Quantic Kyuu 65%', 'Quantic Kyuu 65%'), ('Rama Kara', 'Rama Kara'), ('Rama Koyu', 'Rama Koyu'), ('Rama M60-A', 'Rama M60-A'), ('Rama M60-A SEQ2', 'Rama M60-A SEQ2'), ('Rama M65-A', 'Rama M65-A'), ('Rama M65-B', 'Rama M65-B'), ('Rama U80-A SEQ2', 'Rama U80-ASEQ2'), ('Reconsiderit Southpaw 65+', 'Reconsiderit Southpaw 65+'), ('Salamander TKL', 'Salamander TKL'), ('Satisfaction 75', 'Satisfaction 75'), ('Satisfaction 75 r2', 'Satisfaction 75 r2'), ('Smith + Rune Iron 165', 'Smith + Rune Iron 165'), ('Smith + Rune Iron 180', 'Smith + Rune Iron 180'), ('TGR 910', 'TGR 910'), ('TGR Alice', 'TGR Alice'), ('TGR Jane', 'TGR Jane'), ('TGR Jane v2', 'TGR Jane v2'), ('TGR Jane v2 CE', 'TGR Jane v2 CE'), ('The Key Company CandyBar Premium', 'The Key Company CandyBar Premium'), ('Think 6.5 v1', 'Think 6.5 v1'), ('Think 6.5 v2', 'Think 6.5 v2'), ('Wilba.Tech Thermal', 'Wilba.Tech Thermal'), ('Xeno', 'Xeno'), ('Zambumon Sar', 'Zambumon Sar'), ('Zambumon Verne', 'Zambumon Verne'), ('Other', 'Other')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='pcb',
            field=models.CharField(blank='False', choices=[('Hotswap', 'Hotswap'), ('No PCB(handwired)', 'No PCB(handwired)'), ('Solderable', 'Solderable')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='plate',
            field=models.CharField(blank='False', choices=[('Titanium', 'Titanium'), ('Brass Half Plate', 'Brass Half Plate'), ('Carbon Fiber Half Plate', 'Carbon Fiber Half Plate'), ('Carbon Fiber', 'Carbon Fiber'), ('Aluminum', 'Aluminum'), ('Integrated', 'Integrated'), ('Stainless Steel', 'Stainless Steel'), ('Brass', 'Brass'), ('Other', 'Other'), ('Titanium Half Plate', 'Titanium Half Plate'), ('POM Half Plate', 'POM Half Plate'), ('Integrated Half Plate', 'Integrated Half Plate'), ('Polycarbonate', 'Polycarbonate'), ('Acrylic', 'Acrylic'), ('Stainless Steel Half Plate', 'Stainless Steel Half Plate'), ('Acrylic Half Plate', 'Acrylic Half Plate'), ('Aluminum Half Plate', 'Aluminum Half Plate'), ('Polycarbonate Half Plate', 'Polycarbonate Half Plate'), ('None', 'None'), ('POM', 'POM')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='stabilizers',
            field=models.CharField(blank='False', choices=[('Others', 'Others'), ('Durock Stabilizers', 'Durock Stabilizers'), ('C3 Equalz Stabilizers', 'C3 Equalz Stabilizers'), ('Cherry Stabilizers', 'Cherry Stabilizers'), ('EverGlide Stabilizers', 'EverGlide Stabilizers'), ('Zeal PC Stabilizers', 'Zeal PC Stabilizers'), ('None', 'None')], max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='switches',
            field=models.CharField(blank='False', choices=[('Kailh Pro Heavy Plum', 'Kailh Pro Heavy Plum'), ('Zeal Sakurio', 'Zeal Sakurio'), ('C3 Tangerines', 'C3 Tangerines'), ('Others', 'Others'), ('Kailh Pro Purple', 'Kailh Pro Purple'), ('Kailh Pro Heavy Berry', 'Kailh Pro Heavy Berry'), ('Cherry MX Brown', 'Cherry MX Brown'), ('Zeal Tealio', 'Zeal Tealio'), ('Zeal Zealio', 'Zeal Zealio'), ('Gateron Silent Inks', 'Gateron Silent Inks'), ('Kailh Pro Heavy Sage', 'Kailh Pro Heavy Sage'), ('Gateron Brown', 'Gateron Brown'), ('Gateron Silent Red', 'Gateron Silent Red'), ('Kailh Red', 'Kailh Red'), ('Gateron Yellow', 'Gateron Yellow'), ('Kailh Blue', 'Kailh Blue'), ('Cherry MX Silent Red', 'Cherry MX Silent Red'), ('Gateron Blue', 'Gateron Blue'), ('Kailh Brown', 'Kailh Brown'), ('Cherry MX Speed Silvers', 'Cherry MX Speed Silvers'), ('Kailh Box Navy', 'Kailh Box Navy'), ('Cherry MX Clear', 'Cherry MX Clear'), ('Cherry MX Blue', 'Cherry MX Blue'), ('Kailh Pro Light Green', 'Kailh Pro Light Green'), ('Drop Holy Pandas', 'Drop Holy Pandas'), ('Kailh Black', 'Kailh Black'), ('Gateron Silent Black', 'Gateron Silent Black'), ('Kailh Pro Burgundy', 'Kailh Pro Burgundy'), ('Gateron Silent Brown', 'Gateron Silent Brown'), ('Cherry MX Yellow', 'Cherry MX Yellow'), ('Gateron Clear', 'Gateron Clear'), ('Cherry MX Red', 'Cherry MX Red'), ('Gateron Green', 'Gateron Green'), ('Cherry MX Silent Black', 'Cherry MX Silent Black'), ('Gateron Red', 'Gateron Red'), ('Zeal Roselio', 'Zeal Roselio'), ('Cherry MX White', 'Cherry MX White'), ('Cherry MX Black', 'Cherry MX Black'), ('Gateron Silent Clear', 'Gateron Silent Clear'), ('Gateron Black', 'Gateron Black'), ('Zeal Healio', 'Zeal Healio'), ('Cherry MX Grey', 'Cherry MX Grey'), ('Gateron Inks', 'Gateron Inks'), ('Cherry MX Green', 'Cherry MX Green'), ('Zeal Zilent', 'Zeal Zilent'), ('Gateron Silent Yellow', 'Gateron Silent Yellow')], default='', max_length=50),
        ),
    ]
