# Generated by Django 2.2.5 on 2020-12-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0003_auto_20201217_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='pcb',
            field=models.CharField(blank='False', choices=[('Solderable', 'Solderable'), ('Hotswap', 'Hotswap'), ('No PCB(handwired)', 'No PCB(handwired)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='plate',
            field=models.CharField(blank='False', choices=[('Acrylic', 'Acrylic'), ('Acrylic Half Plate', 'Acrylic Half Plate'), ('Aluminum', 'Aluminum'), ('Aluminum Half Plate', 'Aluminum Half Plate'), ('Brass', 'Brass'), ('Brass Half Plate', 'Brass Half Plate'), ('Carbon Fiber', 'Carbon Fiber'), ('Carbon Fiber Half Plate', 'Carbon Fiber Half Plate'), ('Integrated', 'Integrated'), ('Integrated Half Plate', 'Integrated Half Plate'), ('Polycarbonate', 'Polycarbonate'), ('Polycarbonate Half Plate', 'Polycarbonate Half Plate'), ('POM', 'POM'), ('POM Half Plate', 'POM Half Plate'), ('Stainless Steel', 'Stainless Steel'), ('Stainless Steel Half Plate', 'Stainless Steel Half Plate'), ('Titanium', 'Titanium'), ('Titanium Half Plate', 'Titanium Half Plate'), ('Other', 'Other'), ('None', 'None')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='stabilizers',
            field=models.CharField(blank='False', choices=[('C3 Equalz Stabilizers', 'C3 Equalz Stabilizers'), ('Cherry Stabilizers', 'Cherry Stabilizers'), ('EverGlide Stabilizers', 'EverGlide Stabilizers'), ('Durock Stabilizers', 'Durock Stabilizers'), ('Zeal PC Stabilizers', 'Zeal PC Stabilizers'), ('Others', 'Others'), ('None', 'None')], max_length=30),
        ),
        migrations.AlterField(
            model_name='keyboardlist',
            name='switches',
            field=models.CharField(blank='False', choices=[('C3 Tangerines', 'C3 Tangerines'), ('Cherry MX Black', 'Cherry MX Black'), ('Cherry MX Blue', 'Cherry MX Blue'), ('Cherry MX Brown', 'Cherry MX Brown'), ('Cherry MX Clear', 'Cherry MX Clear'), ('Cherry MX Green', 'Cherry MX Green'), ('Cherry MX Grey', 'Cherry MX Grey'), ('Cherry MX Red', 'Cherry MX Red'), ('Cherry MX Silent Black', 'Cherry MX Silent Black'), ('Cherry MX Silent Red', 'Cherry MX Silent Red'), ('Cherry MX Speed Silvers', 'Cherry MX Speed Silvers'), ('Cherry MX White', 'Cherry MX White'), ('Cherry MX Yellow', 'Cherry MX Yellow'), ('Kailh Black', 'Kailh Black'), ('Kailh Blue', 'Kailh Blue'), ('Kailh Brown', 'Kailh Brown'), ('Kailh Red', 'Kailh Red'), ('Kailh Box Navy', 'Kailh Box Navy'), ('Kailh Pro Burgundy', 'Kailh Pro Burgundy'), ('Kailh Pro Purple', 'Kailh Pro Purple'), ('Kailh Pro Light Green', 'Kailh Pro Light Green'), ('Kailh Pro Heavy Berry', 'Kailh Pro Heavy Berry'), ('Kailh Pro Heavy Plum', 'Kailh Pro Heavy Plum'), ('Kailh Pro Heavy Sage', 'Kailh Pro Heavy Sage'), ('Gateron Black', 'Gateron Black'), ('Gateron Blue', 'Gateron Blue'), ('Gateron Brown', 'Gateron Brown'), ('Gateron Clear', 'Gateron Clear'), ('Gateron Green', 'Gateron Green'), ('Gateron Inks', 'Gateron Inks'), ('Gateron Red', 'Gateron Red'), ('Gateron Yellow', 'Gateron Yellow'), ('Gateron Silent Black', 'Gateron Silent Black'), ('Gateron Silent Brown', 'Gateron Silent Brown'), ('Gateron Silent Clear', 'Gateron Silent Clear'), ('Gateron Silent Inks', 'Gateron Silent Inks'), ('Gateron Silent Red', 'Gateron Silent Red'), ('Gateron Silent Yellow', 'Gateron Silent Yellow'), ('Drop Holy Pandas', 'Drop Holy Pandas'), ('Zeal Healio', 'Zeal Healio'), ('Zeal Tealio', 'Zeal Tealio'), ('Zeal Roselio', 'Zeal Roselio'), ('Zeal Sakurio', 'Zeal Sakurio'), ('Zeal Zealio', 'Zeal Zealio'), ('Zeal Zilent', 'Zeal Zilent'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
