# Generated by Django 2.2.5 on 2020-12-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0005_auto_20201218_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='stabilizers',
            field=models.CharField(choices=[('C3 Equalz Stabilizers', 'C3 Equalz Stabilizers'), ('Cherry Stabilizers', 'Cherry Stabilizers'), ('EverGlide Stabilizers', 'EverGlide Stabilizers'), ('Durock Stabilizers', 'Durock Stabilizers'), ('Zeal PC Stabilizers', 'Zeal PC Stabilizers'), ('Others', 'Others'), ('None', 'None')], default='', max_length=30),
        ),
    ]
