# Generated by Django 2.2.5 on 2020-12-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0006_auto_20201218_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
