# Generated by Django 2.2.5 on 2020-12-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MechKeyboardsApp', '0008_auto_20201218_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardlist',
            name='username',
            field=models.CharField(default='', max_length=80),
        ),
    ]
