# Generated by Django 2.2.5 on 2021-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(blank=True, default='', max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000, max_length=0.0)),
                ('measurement', models.CharField(choices=[('cups', 'cups'), ('tablespoons', 'tablespoons'), ('teaspoon', 'teaspoon'), ('ounces', 'ounces'), ('grams', 'grams')], max_length=60)),
            ],
        ),
    ]
