# Generated by Django 2.2.5 on 2021-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speedster', '0003_auto_20210120_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
