# Generated by Django 2.2.5 on 2021-10-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatCheck', '0002_auto_20211004_1528'),
        ('StatCheck', '0002_auto_20211005_1435'),
    ]

    operations = [
    ]
