# Generated by Django 2.2.5 on 2021-07-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreciousMetals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciousmetalsitem',
            name='ounces',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
