# Generated by Django 2.2.5 on 2021-07-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreciousMetals', '0003_auto_20210713_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciousmetalsitem',
            name='type',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold')], max_length=10),
        ),
    ]
