# Generated by Django 2.2.5 on 2021-07-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreciousMetals', '0004_auto_20210713_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciousmetalsitem',
            old_name='age',
            new_name='year',
        ),
    ]
