# Generated by Django 2.2.5 on 2021-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreciousMetals', '0005_auto_20210713_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciousmetalsitem',
            name='form',
            field=models.CharField(choices=[('Coin', 'Coin'), ('Bar', 'Bar'), ('Raw', 'Raw')], max_length=10),
        ),
    ]
