# Generated by Django 2.2.5 on 2021-09-08 18:40


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('URL', models.CharField(default='', max_length=60)),
                ('free_version', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('key_features', models.TextField(max_length=200)),
            ],
        ),
    ]
