# Generated by Django 2.2.5 on 2020-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=60)),
                ('network', models.CharField(max_length=60)),
                ('seasons', models.IntegerField()),
            ],
        ),
    ]
