# Generated by Django 2.2.5 on 2020-12-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVshowAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='seasons',
            field=models.PositiveIntegerField(),
        ),
    ]
