# Generated by Django 2.2.5 on 2020-12-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVshowAPP', '0003_tvshows_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshows',
            name='summary',
        ),
    ]
