# Generated by Django 2.2.5 on 2020-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVshowAPP', '0004_remove_tvshows_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='summary',
            field=models.CharField(default='What is the show about?', max_length=500),
        ),
    ]
