# Generated by Django 2.2.5 on 2020-12-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVshowAPP', '0005_tvshows_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='summary',
            field=models.TextField(default='What is the show about?', max_length=500),
        ),
    ]
