# Generated by Django 2.2.5 on 2021-10-13 00:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RvtFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revit_title', models.CharField(blank=True, default='', max_length=80)),
                ('revit_description', models.TextField(blank=True, default='', max_length=300)),
                ('revit_category', models.CharField(choices=[('0 Revit Basic', '0 Revit Basic'), ('1 Revit Modeling', '1 Revit Modeling'), ('2 Revit Documentation', '2 Revit Documentation'), ('3 Revit Collaboration', '3 Revit Collaboration'), ('4 Revit Plug-ins', '4 Revit Plug-ins'), ('5 Revit Maintenance', '5 Revit Maintenance'), ('6 BIM360', '6 BIM360'), ('7 Revit Troubleshoot', '7 Revit Troubleshoot')], max_length=80)),
                ('revit_level', models.CharField(choices=[('0 Novice', '0 Novice'), ('1 Beginner', '1 Beginner'), ('2 Intermediate', '2 Intermediate'), ('3 Advance', '3 Advance')], max_length=80)),
                ('job_category', models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Designer & Production', '3 Designer & Production'), ('4 Administration', '4 Administration'), ('5 Project Lead', '5 Project Lead')], max_length=80)),
                ('google_keywords', models.CharField(blank=True, default='', max_length=100)),
            ],
            managers=[
                ('RvtFunctions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=80)),
                ('revit_level', models.CharField(choices=[('0 Novice', '0 Novice'), ('1 Beginner', '1 Beginner'), ('2 Intermediate', '2 Intermediate'), ('3 Advance', '3 Advance')], max_length=80)),
                ('job_category', models.CharField(choices=[('0 All', '0 All'), ('1 Designer', '1 Designer'), ('2 Production', '2 Production'), ('3 Designer & Production', '3 Designer & Production'), ('4 Administration', '4 Administration'), ('5 Project Lead', '5 Project Lead')], max_length=80)),
            ],
            managers=[
                ('Users', django.db.models.manager.Manager()),
            ],
        ),
    ]
