# Generated by Django 2.2.5 on 2021-02-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
