# Generated by Django 2.2.5 on 2021-02-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubApp', '0002_remove_book_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
