# Generated by Django 2.2.5 on 2021-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubApp', '0003_auto_20210219_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
