# Generated by Django 2.2.5 on 2021-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubApp', '0004_book_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
