# Generated by Django 2.2.5 on 2021-02-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClubApp', '0005_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
