# Generated by Django 2.2.5 on 2021-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCarParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=60)),
                ('make', models.CharField(choices=[('Subaru', 'Subaru'), ('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Chevy', 'Chevy'), ('Mercedes-benz', 'Mercedes-benz')], default='', max_length=15)),
                ('car_Model', models.CharField(blank=True, default='', max_length=60)),
                ('year', models.CharField(choices=[('1990', '1990'), ('1995', '1995'), ('2000', '2000'), ('2005', '2005'), ('2010', '2010'), ('2015', '2015'), ('2020', '2020')], default='', max_length=6)),
                ('part', models.TextField(blank=True, default='', max_length=300)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
