# Generated by Django 2.2.5 on 2021-08-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('highlights', models.CharField(choices=[('location', 'location'), ('good food', 'good food'), ('ambiance', 'ambiance'), ('stiff pour', 'stiff pour'), ('late night HH', 'late night HH'), ('good drinks', 'good drinks'), ('dietary options', 'dietary options'), ('budget friendly', 'budget friendly')], max_length=50)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.CharField(choices=[('three star', 'three star'), ('one star', 'one star'), ('five star', 'five star'), ('four star', 'four star'), ('two star', 'two star')], max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
