# Generated by Django 2.2.5 on 2021-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Seasons', models.IntegerField(default='')),
                ('Player_Efficiency_Rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Points_Per_Game', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Win_Shares', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Hall_of_Fame', models.BooleanField(default=False)),
            ],
        ),
    ]
