# Generated by Django 2.2.5 on 2021-08-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazerStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Hall_of_Fame',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
    ]
