# Generated by Django 2.2.5 on 2021-10-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('what_position', models.CharField(max_length=30)),
                ('what_number', models.IntegerField()),
                ('strong_feet', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_location', models.CharField(max_length=30)),
                ('head_coach', models.CharField(max_length=30)),
                ('team_mascot', models.CharField(max_length=30)),
                ('team_record', models.IntegerField()),
            ],
        ),
    ]
