# Generated by Django 2.2.5 on 2021-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=80)),
                ('Phone', models.IntegerField()),
                ('MovieType', models.CharField(choices=[('First Run', 'First Run'), ('Previously Released', 'Previously Released'), ('Independent', 'Independent')], max_length=20)),
                ('SeatType', models.CharField(choices=[('Stadium', 'Stadium'), ('Deluxe Reclinable', 'Deluxe Reclinable'), ('Couches', 'Couches'), ('Other', 'Other')], max_length=20)),
                ('HasAlcohol', models.CharField(choices=[('No Alcohol', 'No Alcohol'), ('Full Bar', 'Full Bar'), ('Beer', 'Beer'), ('Wine', 'Wine'), ('Beer and Wine', 'Beer and Wine'), ('Liquor', 'Liquor')], max_length=20)),
                ('Food', models.CharField(choices=[('Popcorn and Candy', 'Popcorn and Candy'), ('Pizza and Snacks', 'Pizza and Snacks'), ('Full Menu', 'Full Menu')], max_length=20)),
            ],
        ),
    ]
