# Generated by Django 2.2.5 on 2021-05-03 14:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=300)),
                ('travel_date', models.DateField(blank=True, null=True)),
            ],
            managers=[
                ('TravelDestinations', django.db.models.manager.Manager()),
            ],
        ),
    ]
