# Generated by Django 2.2.5 on 2021-05-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDestinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldestinations',
            old_name='activity',
            new_name='Activity',
        ),
        migrations.RenameField(
            model_name='traveldestinations',
            old_name='city_name',
            new_name='City_Name',
        ),
        migrations.RenameField(
            model_name='traveldestinations',
            old_name='country_name',
            new_name='Country_Name',
        ),
        migrations.RenameField(
            model_name='traveldestinations',
            old_name='travel_date',
            new_name='Travel_Date',
        ),
    ]
