# Generated by Django 2.2.5 on 2021-05-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDestinations', '0002_auto_20210503_1130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='traveldestinations',
            managers=[
            ],
        ),
    ]
