# Generated by Django 2.2.5 on 2021-10-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('username', models.CharField(default='', max_length=10)),
                ('skate_brand', models.CharField(blank=True, choices=[('Bont', 'Bont'), ('Flyke', 'Flyke'), ('Luigino Verducci', 'Luigino Verducci'), ('Powerslide', 'Powerslide'), ('Riedell', 'Riedell'), ('Rollerblade', 'Rollerblade'), ('Vanilla', 'Vanilla')], default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=20)),
                ('boot_materials', models.CharField(blank=True, choices=[('Leather/Fiberglass', 'Leather/Fiberglass'), ('Leather/Carbon Fiber', 'Leather/Carbon Fiber'), ('Leather/Resin', 'Leather/Resin')], default='', max_length=20)),
                ('boot_style', models.CharField(blank=True, choices=[('Low Ankle', 'Low Ankle'), ('High Ankle', 'High Ankle')], default='', max_length=20)),
                ('frame', models.CharField(blank=True, choices=[('Aluminum', 'Aluminum'), ('Carbon Fiber', 'Carbon Fiber'), ('Composite', 'Composite'), ('Steel', 'Steel')], default='', max_length=15)),
                ('bearings_rating', models.CharField(blank=True, choices=[('ABEC (Below 7)', 'ABEC (Below 7)'), ('ABEC-7', 'ABEC-7'), ('ABEC-8', 'ABEC-8'), ('ABEC-9', 'ABEC-9'), ('Bones', 'Bones'), ('Swiss', 'Swiss')], default='', max_length=10)),
                ('bearings_material', models.CharField(blank=True, choices=[('Ceramic', 'Ceramic'), ('Steel', 'Steel'), ('Other', 'Other')], default='', max_length=7)),
                ('comfort', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Above Average', 'Above Average')], default='', max_length=13)),
                ('overall_rating', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Average', 'Average'), ('Good', 'Good'), ('Above Average', 'Above Average')], default='', max_length=13)),
                ('pros', models.TextField(blank=True, default='', max_length=100)),
                ('cons', models.TextField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
