# Generated by Django 2.2.5 on 2021-07-19 01:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Account', django.db.models.manager.Manager()),
            ],
        ),
    ]
