# Generated by Django 2.2.5 on 2021-07-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventory', '0002_auto_20210718_2134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
