# Generated by Django 2.2.5 on 2021-09-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('anime', models.CharField(default='', max_length=60)),
                ('release', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('supernatural', 'supernatural'), ('action', 'action'), ('sports', 'sports'), ('life', 'life')], max_length=50)),
                ('episodes', models.CharField(max_length=200)),
            ],
        ),
    ]
