# Generated by Django 2.2.5 on 2021-04-13 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='(000)000-0000', max_length=12)),
                ('address', models.CharField(default='', max_length=95)),
                ('city', models.CharField(default='Portland', max_length=15)),
                ('rating', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
