# Generated by Django 2.2.5 on 2021-04-13 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyThai.Restaurant')),
            ],
        ),
    ]
