# Generated by Django 2.2.5 on 2021-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0002_auto_20210413_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='dishName',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dish',
            name='dishType',
            field=models.CharField(choices=[('Curry', 'Curry'), ('Noodles', 'Noodles'), ('Soup', 'Soup'), ('Appetizers', 'Appetizers')], default='', max_length=10),
        ),
    ]
