# Generated by Django 2.2.5 on 2021-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0004_remove_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
