# Generated by Django 2.2.5 on 2021-04-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0005_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='(000)000-0000', max_length=13),
        ),
    ]
