# Generated by Django 2.2.5 on 2021-04-14 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0007_auto_20210414_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishType',
            field=models.CharField(choices=[('----', '-----'), ('Curry', 'Curry'), ('Noodles', 'Noodles'), ('Soup', 'Soup'), ('Appetizers', 'Appetizers'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=95),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
