# Generated by Django 2.2.5 on 2021-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyThai', '0008_auto_20210414_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishType',
            field=models.CharField(choices=[('Curry', 'Curry'), ('Noodles', 'Noodles'), ('Soup', 'Soup'), ('Appetizers', 'Appetizers'), ('Other', 'Other')], max_length=10),
        ),
    ]
