# Generated by Django 2.2.5 on 2021-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('atk_stab', models.IntegerField(max_length=5)),
                ('atk_slash', models.IntegerField(max_length=5)),
                ('atk_crush', models.IntegerField(max_length=5)),
                ('atk_magic', models.IntegerField(max_length=5)),
                ('atk_range', models.IntegerField(max_length=5)),
                ('def_stab', models.IntegerField(max_length=5)),
                ('def_slash', models.IntegerField(max_length=5)),
                ('def_crush', models.IntegerField(max_length=5)),
                ('def_magic', models.IntegerField(max_length=5)),
                ('def_range', models.IntegerField(max_length=10)),
                ('bns_strength', models.IntegerField(max_length=10)),
                ('bns_range', models.IntegerField(max_length=10)),
                ('bns_magic', models.IntegerField(max_length=10)),
                ('bns_prayer', models.IntegerField(max_length=10)),
                ('slot', models.CharField(blank=True, default='', max_length=60)),
                ('speed', models.IntegerField(max_length=10)),
                ('range', models.IntegerField(max_length=10)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
