# Generated by Django 2.2.5 on 2021-03-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='atk_crush',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_magic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_slash',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_stab',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_magic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_prayer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_strength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_crush',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_magic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_slash',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_stab',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
