# Generated by Django 2.2.5 on 2021-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0004_auto_20210404_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='atk_crush',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_slash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='atk_stab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_prayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='bns_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_crush',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_slash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='def_stab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Head', 'Head'), ('Cape', 'Cape'), ('Neck', 'Neck'), ('Ammunition', 'Ammunition'), ('Weapon', 'Weapon'), ('Shield', 'Shield'), ('Body', 'Body'), ('Legs', 'Legs'), ('Hands', 'Hands'), ('Feet', 'Feet'), ('Ring', 'Ring')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
