# Generated by Django 2.2.5 on 2020-11-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=180, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=180, verbose_name='Movement Title')),
                ('order_number', models.IntegerField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassicalMusic.Composition')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Musician name')),
                ('sort_name', models.CharField(default='', max_length=120, verbose_name='Musician sort name')),
                ('type', models.CharField(choices=[('individual', 'individual'), ('ensemble', 'ensemble')], max_length=20, verbose_name='Type')),
                ('gender', models.CharField(blank=True, default='', max_length=120, verbose_name='Musician gender')),
                ('Life_begin', models.CharField(blank=True, default='', max_length=20, verbose_name='Life begin')),
                ('Life_end', models.CharField(blank=True, default='', max_length=20, verbose_name='Life end')),
                ('life_ended', models.BooleanField(blank=True, null=True, verbose_name='Deceased/Dissolved')),
                ('image_url', models.CharField(blank=True, default='', max_length=80, verbose_name='Image URL')),
                ('MBID', models.CharField(blank=True, default='', max_length=80, verbose_name='Musician MBID')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=180, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=120, verbose_name='Role')),
                ('type', models.CharField(choices=[('individual', 'individual'), ('ensemble', 'ensemble')], max_length=20, verbose_name='Type')),
                ('role_type', models.CharField(choices=[('author_type', 'Composer, lyricist, etc'), ('performer', 'performer')], max_length=20, verbose_name='Type of contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk', models.CharField(default='', max_length=180, verbose_name='Disk')),
                ('track_number', models.IntegerField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClassicalMusic.Movement')),
                ('performers', models.ManyToManyField(to='ClassicalMusic.Musician')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassicalMusic.Release')),
            ],
        ),
        migrations.AddField(
            model_name='musician',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ClassicalMusic.Role'),
        ),
        migrations.AddField(
            model_name='composition',
            name='authors',
            field=models.ManyToManyField(to='ClassicalMusic.Musician'),
        ),
        migrations.AddField(
            model_name='composition',
            name='instrumentation',
            field=models.ManyToManyField(to='ClassicalMusic.Role'),
        ),
    ]
