# Generated by Django 2.2.5 on 2020-11-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicalMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Image URL'),
        ),
    ]
