# Generated by Django 2.2.5 on 2021-05-01 07:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baseball_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('P', 'P'), ('C', 'C'), ('1B', '1B'), ('2B', '2B'), ('3B', '3B'), ('SS', 'SS'), ('LF', 'LF'), ('CF', 'CF'), ('RF', 'RF'), ('DH', 'DH')], max_length=2)),
                ('bats_throws', models.CharField(choices=[('R/R', 'R/R'), ('R/L', 'R/L'), ('L/L', 'L/L'), ('L/R', 'L/R'), ('S/R', 'S/R'), ('S/L', 'S/L')], max_length=3)),
                ('career_ba_or_era', models.DecimalField(decimal_places=3, max_digits=5)),
                ('career_hr_or_so', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            managers=[
                ('baseball_cards', django.db.models.manager.Manager()),
            ],
        ),
    ]
