# Generated by Django 2.2.5 on 2021-05-03 03:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballCards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='baseball_card',
            new_name='BaseballCard',
        ),
        migrations.AlterModelManagers(
            name='baseballcard',
            managers=[
                ('BaseballCards', django.db.models.manager.Manager()),
            ],
        ),
    ]
