# Generated by Django 2.2.5 on 2021-05-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballCards', '0002_auto_20210502_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballcard',
            name='career_hr_or_so',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
