# Generated by Django 2.2.5 on 2021-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballCards', '0003_auto_20210504_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballcard',
            name='career_hr_or_so',
            field=models.IntegerField(),
        ),
    ]
