# Generated by Django 2.2.5 on 2020-12-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, default='', max_length=100)),
                ('artist_name', models.CharField(blank=True, default='', max_length=60)),
                ('release_year', models.PositiveIntegerField(default=1990)),
                ('number_of_tracks', models.PositiveIntegerField(default=1)),
                ('genre', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, default='', max_length=60)),
                ('group_or_solo', models.CharField(choices=[('group', 'group'), ('solo', 'solo')], max_length=5)),
                ('genre', models.CharField(blank=True, default='', max_length=20)),
                ('year_formed', models.PositiveIntegerField(default=1900)),
                ('active', models.BooleanField()),
                ('image_url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SongNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(blank=True, default='', max_length=100)),
                ('artist_name', models.CharField(blank=True, default='', max_length=80)),
                ('album_name', models.CharField(blank=True, default='', max_length=200)),
                ('song_length', models.CharField(blank=True, default='', max_length=50)),
                ('release_year', models.PositiveIntegerField(default=1990)),
            ],
        ),
    ]
