# Generated by Django 2.2.5 on 2020-12-31 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumnames',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='songnames',
            name='release_year',
        ),
        migrations.AddField(
            model_name='albumnames',
            name='album_release_year',
            field=models.PositiveIntegerField(blank=True, default=1990),
        ),
        migrations.AddField(
            model_name='albumnames',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='songnames',
            name='song_release_year',
            field=models.PositiveIntegerField(blank=True, default=1990),
        ),
        migrations.AlterField(
            model_name='albumnames',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.MusicalArtists'),
        ),
        migrations.AlterField(
            model_name='albumnames',
            name='number_of_tracks',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='musicalartists',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='musicalartists',
            name='year_formed',
            field=models.PositiveIntegerField(blank=True, default=1900),
        ),
        migrations.AlterField(
            model_name='songnames',
            name='album_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.AlbumNames'),
        ),
        migrations.AlterField(
            model_name='songnames',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.MusicalArtists'),
        ),
    ]
