# Generated by Django 2.2.5 on 2020-12-31 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0002_auto_20201230_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumnames',
            name='album_release_year',
        ),
        migrations.AddField(
            model_name='albumnames',
            name='date_album_released',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Album Released'),
        ),
    ]
