# Generated by Django 2.2.5 on 2020-12-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_auto_20201230_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumnames',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='songnames',
            name='album_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='songnames',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
