# Generated by Django 2.2.5 on 2021-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_Maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Entrees', 'Entrees'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], max_length=60)),
                ('recipe_name', models.CharField(default='', max_length=100)),
                ('recipe_ingredients', models.TextField(default="Please write you're ingredients and amounts")),
                ('recipe_instructions', models.TextField(default='Please write your instructions here')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='RecipeName',
        ),
    ]
