# Generated by Django 2.2.5 on 2020-11-28 17:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_title', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=60)),
                ('created_date', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
            ],
            managers=[
                ('Art', django.db.models.manager.Manager()),
            ],
        ),
    ]
