# Generated by Django 2.2.5 on 2020-12-07 21:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='art',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
