# Generated by Django 2.2.5 on 2021-03-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
            ],
        ),
    ]
