# Generated by Django 2.2.5 on 2021-03-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0002_auto_20210302_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
