# Generated by Django 2.2.5 on 2021-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0003_auto_20210302_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=200)),
            ],
        ),
    ]
