# Generated by Django 2.2.5 on 2021-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0005_auto_20210305_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facts',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('OR', 'OR'), ('WA', 'WA'), ('FL', 'FL'), ('HI', 'HI'), ('TX', 'TX')], max_length=200),
        ),
        migrations.AlterField(
            model_name='facts',
            name='town',
            field=models.CharField(choices=[('Boaz', 'Boaz'), ('Portland', 'Portland'), ('Seattle', 'Seattle'), ('Miami', 'Miami'), ('Hilo', 'Hilo'), ('El Paso', 'El Paso')], max_length=200),
        ),
    ]
