# Generated by Django 2.2.5 on 2021-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0006_auto_20210305_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'AL'), ('OR', 'OR'), ('WA', 'WA'), ('FL', 'FL'), ('HI', 'HI'), ('TX', 'TX')], default='', max_length=200),
        ),
    ]
