# Generated by Django 2.2.5 on 2021-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0007_auto_20210305_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='facts',
            name='town',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='facts',
            table='Facts',
        ),
    ]
