# Generated by Django 2.2.5 on 2021-03-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0008_auto_20210307_1149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facts',
            table=None,
        ),
    ]
