# Generated by Django 2.2.5 on 2021-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0009_auto_20210308_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
