# Generated by Django 2.2.5 on 2021-03-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0011_auto_20210308_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='date',
            field=models.DateField(),
        ),
    ]
