# Generated by Django 2.2.5 on 2021-03-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0012_auto_20210308_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
