# Generated by Django 2.2.5 on 2021-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0013_auto_20210308_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
