# Generated by Django 2.2.5 on 2021-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0014_auto_20210309_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='date',
            field=models.DateField(),
        ),
    ]
