# Generated by Django 2.2.5 on 2021-03-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwesomeWeather', '0015_auto_20210309_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='event',
            field=models.TextField(max_length=2000),
        ),
    ]
