# Generated by Django 2.2.5 on 2021-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='subject',
            field=models.CharField(choices=[('Cheerful', 'Cheerful'), ('Reflective', 'Reflective'), ('Gloomy', 'Gloomy'), ('Humorous', 'Humorous'), ('Melancholy', 'Melancholy'), ('Idyllic', 'Idyllic'), ('Whimsical', 'Whimsical'), ('Romantic', 'Romantic'), ('Mysterious', 'Mysterious'), ('Ominous', 'Ominous'), ('Calm', 'Calm'), ('Lighthearted', 'Lighthearted'), ('Hopeful', 'Hopeful'), ('Angry', 'Angry'), ('Fearful', 'Fearful'), ('Tense', 'Tense'), ('Lonely', 'Lonely'), ('Inspirational', 'Inspirational')], max_length=50),
        ),
    ]
