# Generated by Django 2.2.5 on 2021-07-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
