# Generated by Django 2.2.5 on 2021-07-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumReviews', '0002_album_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Review',
            field=models.TextField(default='Type your review here (optional)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
