# Generated by Django 2.2.5 on 2021-07-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumReviews', '0003_auto_20210728_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Year',
            field=models.IntegerField(default=2021),
        ),
    ]
