# Generated by Django 2.2.5 on 2021-02-27 01:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('OR', 'Oregon'), ('WA', 'Washington')], max_length=2)),
                ('type', models.CharField(choices=[('Dispersed', 'Dispersed'), ('Developed', 'Developed')], max_length=9)),
                ('access', models.CharField(choices=[('Drive-up', 'Drive-up'), ('Hike-in', 'Hike-in')], max_length=8)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('directions', models.CharField(blank=True, max_length=500, null=True)),
            ],
            managers=[
                ('Campsites', django.db.models.manager.Manager()),
            ],
        ),
    ]
