# Generated by Django 2.2.5 on 2021-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0002_auto_20210228_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='state',
            field=models.CharField(choices=[('OR', 'OR'), ('WA', 'WA')], max_length=2),
        ),
    ]
