# Generated by Django 2.2.5 on 2021-03-03 02:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0003_auto_20210301_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('full_link', models.URLField(blank=True, null=True)),
            ],
            managers=[
                ('NFSites', django.db.models.manager.Manager()),
            ],
        ),
    ]
