# Generated by Django 2.2.5 on 2021-03-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0004_nfsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFSite',
        ),
    ]
