# Generated by Django 2.2.5 on 2021-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensive_stats',
            name='blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defensive_stats',
            name='defRebs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defensive_stats',
            name='steals',
            field=models.IntegerField(default=0),
        ),
    ]
