# Generated by Django 2.2.5 on 2021-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0003_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
