# Generated by Django 2.2.5 on 2021-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0005_auto_20210722_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=60)),
                ('defRebs', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerDatabase',
        ),
    ]
