# Generated by Django 2.2.5 on 2021-07-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0007_favoritesdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesdb',
            name='blocks',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='defRebs',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='playerName',
            field=models.CharField(editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='steals',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='total',
            field=models.IntegerField(editable=False),
        ),
    ]
