# Generated by Django 2.2.5 on 2021-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstats', '0008_auto_20210723_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesdb',
            name='blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='defRebs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='playerName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='steals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favoritesdb',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
