# Generated by Django 2.2.5 on 2021-09-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyShows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=75)),
                ('day_of_week', models.CharField(choices=[('01', 'Sunday'), ('02', 'Monday'), ('03', 'Tuesday'), ('04', 'Wednesday'), ('05', 'Thursday'), ('06', 'Friday'), ('07', 'Saturday')], max_length=20)),
                ('airtime', models.TimeField()),
                ('network', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('year_first_aired', models.SmallIntegerField(max_length=4)),
                ('number_of_seasons', models.SmallIntegerField(max_length=2)),
                ('status', models.CharField(max_length=10)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
