# Generated by Django 2.2.5 on 2021-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP_TrackShows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfo',
            name='number_of_seasons',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='year_first_aired',
            field=models.SmallIntegerField(),
        ),
    ]
