# Generated by Django 2.2.5 on 2021-09-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP_TrackShows', '0002_auto_20210916_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='myshows',
            name='status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Ended', 'Ended')], max_length=10, null=True),
        ),
    ]
