# Generated by Django 2.2.5 on 2021-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP_TrackShows', '0003_auto_20210917_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshows',
            name='day_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
    ]
