# Generated by Django 2.2.5 on 2021-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP_TrackShows', '0005_auto_20210920_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshows',
            name='airtime',
            field=models.TimeField(default='12:00', help_text='HH:MM format'),
        ),
    ]
