# Generated by Django 2.2.5 on 2021-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP_TrackShows', '0006_auto_20210920_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshows',
            name='airtime',
            field=models.TimeField(default='12:00'),
        ),
    ]
