# Generated by Django 2.2.5 on 2021-01-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceHorses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.CharField(blank=True, choices=[('two year olds', 'two year olds'), ('three year olds', 'three year olds'), ('four year olds and up', 'four year olds and up')], default='', max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(blank=True, default='', max_length=200)),
                ('horse_name', models.CharField(blank=True, default='', max_length=100)),
                ('surface', models.CharField(blank=True, choices=[('dirt/all weather', 'dirt/all weather'), ('turf', 'turf')], default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
