# Generated by Django 2.2.5 on 2021-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(blank=True, default='', max_length=200)),
                ('surface', models.CharField(blank=True, choices=[('dirt/all weather', 'dirt/all weather'), ('turf', 'turf')], default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RaceResults',
        ),
    ]
