# Generated by Django 2.2.5 on 2021-01-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0002_auto_20210126_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Races',
        ),
    ]
