# Generated by Django 2.2.5 on 2021-01-27 05:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0003_delete_races'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceHorses',
            new_name='RaceHorse',
        ),
        migrations.AlterModelManagers(
            name='racehorse',
            managers=[
                ('RaceHorses', django.db.models.manager.Manager()),
            ],
        ),
    ]
