# Generated by Django 2.2.5 on 2021-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0004_auto_20210126_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='racehorse',
            name='stats',
            field=models.TextField(blank=True, default='TBA', max_length=255),
        ),
    ]
