# Generated by Django 2.2.5 on 2021-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0005_racehorse_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racehorse',
            name='stats',
        ),
        migrations.AddField(
            model_name='racehorse',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='dam',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='sire',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='speed_figure',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
