# Generated by Django 2.2.5 on 2021-02-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0006_auto_20210130_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racehorse',
            name='color',
        ),
        migrations.RemoveField(
            model_name='racehorse',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='racehorse',
            name='sire',
        ),
        migrations.RemoveField(
            model_name='racehorse',
            name='speed_figure',
        ),
    ]
