# Generated by Django 2.2.5 on 2021-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorseApp', '0007_auto_20210202_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='racehorse',
            name='color',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='dam',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='sire',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='racehorse',
            name='speed_figure',
            field=models.IntegerField(default=0),
        ),
    ]
