# Generated by Django 2.2.5 on 2021-04-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('race', models.CharField(choices=[('Dranei', 'Dranei'), ('Blood Elf', 'Blood Elf'), ('Human', 'Human'), ('Night Elf', 'Night Elf'), ('Undead', 'Undead'), ('Orc', 'Orc'), ('Troll', 'entrees'), ('Gnome', 'Gnome')], max_length=60)),
                ('sex', models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=60)),
                ('backstory', models.TextField(blank=True, default='', max_length=300)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
