# Generated by Django 2.2.5 on 2021-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Dranei', 'Dranei'), ('Undead', 'Undead'), ('Orc', 'Orc'), ('Gnome', 'Gnome'), ('Human', 'Human'), ('Troll', 'entrees'), ('Blood Elf', 'Blood Elf'), ('Night Elf', 'Night Elf')], max_length=60),
        ),
        migrations.AlterField(
            model_name='character_create',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], max_length=60),
        ),
    ]
