# Generated by Django 2.2.5 on 2021-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0002_auto_20210428_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Troll', 'Troll'), ('Dranei', 'Dranei'), ('Night Elf', 'Night Elf'), ('Human', 'Human'), ('Gnome', 'Gnome'), ('Blood Elf', 'Blood Elf'), ('Orc', 'Orc'), ('Undead', 'Undead')], max_length=60),
        ),
    ]
