# Generated by Django 2.2.5 on 2021-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0003_auto_20210428_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Troll', 'Troll'), ('Gnome', 'Gnome'), ('Night Elf', 'Night Elf'), ('Undead', 'Undead'), ('Dranei', 'Dranei'), ('Human', 'Human'), ('Blood Elf', 'Blood Elf'), ('Orc', 'Orc')], max_length=60),
        ),
        migrations.AlterField(
            model_name='character_create',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=60),
        ),
    ]
