# Generated by Django 2.2.5 on 2021-04-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharacterApp', '0004_auto_20210428_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_create',
            name='race',
            field=models.CharField(choices=[('Dranei', 'Dranei'), ('Gnome', 'Gnome'), ('Troll', 'Troll'), ('Blood Elf', 'Blood Elf'), ('Night Elf', 'Night Elf'), ('Undead', 'Undead'), ('Orc', 'Orc'), ('Human', 'Human')], max_length=60),
        ),
        migrations.AlterField(
            model_name='character_create',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Other', 'Other'), ('Female', 'Female')], max_length=60),
        ),
    ]
