# Generated by Django 2.2.5 on 2021-06-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_film', models.CharField(max_length=100)),
                ('Year_of_film', models.IntegerField()),
                ('Film_star_names', models.CharField(max_length=100)),
                ('Director_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
