# Generated by Django 2.2.5 on 2021-06-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0003_auto_20210614_1804'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
    ]
