# Generated by Django 2.2.5 on 2021-06-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SciFiWatchlist', '0005_auto_20210615_1147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movie',
            managers=[
            ],
        ),
    ]
