# Generated by Django 2.2.5 on 2021-01-22 19:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('artist', models.TextField(max_length=60)),
                ('date_listened', models.DateField()),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['artist'],
            },
            managers=[
                ('albums', django.db.models.manager.Manager()),
            ],
        ),
    ]
