# Generated by Django 2.2.5 on 2021-01-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumTracker', '0002_auto_20210122_1304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
            ],
        ),
    ]
