# Generated by Django 2.2.5 on 2020-12-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Platform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Nintendo Entertainment System', 'Nintendo Entertainment System'), ('Super Nintendo Entertainment System', 'Super Nintendo Entertainment System'), ('Sega Genesis', 'Sega Genesis'), ('Sega Dreamcast', 'Sega Dreamcast'), ('Sony Playstation', 'Sony Playstation'), ('Sony Playstation 2', 'Sony Playstation 2'), ('Sony Playstation 3', 'Sony Playstation 3'), ('Sony Playstation 4', 'Sony Playstation 4'), ('Microsoft XBox', 'Microsoft XBox'), ('Microsoft XBox 360', 'Microsoft XBox 360'), ('Microsoft XBox One', 'Microsoft XBox One')], max_length=100)),
                ('Genre', models.CharField(choices=[('Role-Playing Game', 'Role-Playing Game'), ('First-Person Shooter', 'First-Person Shooter'), ('Third-Person Shooter', 'Third-Person shooter'), ('2D Platform', '2D Platform'), ('3D Platform', '3D Platform'), ('Metroidvania', 'Metroidvania'), ('Puzzle', 'Puzzle'), ('Simulation', 'Simulation')], max_length=100)),
                ('Opinion', models.TextField(max_length=500)),
            ],
        ),
    ]
