# Generated by Django 2.2.5 on 2021-04-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_def',
            new_name='word_definition',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word_found',
            new_name='word_in_a_sentence',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_insent',
        ),
        migrations.AddField(
            model_name='word',
            name='where_did_you_find_the_word',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
