# Generated by Django 2.2.5 on 2021-04-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0002_auto_20210408_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etymology',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
