# Generated by Django 2.2.5 on 2021-04-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0003_auto_20210408_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etymology',
            old_name='word_ety',
            new_name='word_name',
        ),
    ]
