# Generated by Django 2.2.5 on 2021-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0004_auto_20210409_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='etymology',
        ),
    ]
