# Generated by Django 2.2.5 on 2021-04-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0005_auto_20210413_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='origin',
            new_name='parent_langauges',
        ),
    ]
