# Generated by Django 2.2.5 on 2021-04-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordNerd', '0006_auto_20210413_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='parent_langauges',
            new_name='parent_languages',
        ),
    ]
