# Generated by Django 2.2.5 on 2021-04-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarinfo',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guitarinfo',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='guitarinfo',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
