# Generated by Django 2.2.5 on 2021-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0002_auto_20210410_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
