SUBJECT = [
    ('Cheerful', 'Cheerful'),
    ('Reflective', 'Reflective'),
    ('Gloomy', 'Gloomy'),
    ('Humorous', 'Humorous'),
    ('Melancholy', 'Melancholy'),
    ('Idyllic', 'Idyllic'),
    ('Whimsical', 'Whimsical'),
    ('Romantic', 'Romantic'),
    ('Mysterious', 'Mysterious'),
    ('Ominous', 'Ominous'),
    ('Calm', 'Calm'),
    ('Lighthearted', 'Lighthearted'),
    ('Hopeful', 'Hopeful'),
    ('Angry', 'Angry'),
    ('Fearful', 'Fearful'),
    ('Tense', 'Tense'),
    ('Lonely', 'Lonely'),
    ('Inspirational', 'Inspirational'),
]