# Generated by Django 2.2.5 on 2021-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('legend', models.CharField(choices=[('Mirage', 'Mirage'), ('Wattson', 'Wattson'), ('Octane', 'Octane'), ('Wraith', 'Wraith'), ('Horizon', 'Horizon'), ('Bloodhound', 'Bloodhound'), ('Revenant', 'Revenant'), ('Valkyrie', 'Valkyrie'), ('Fuse', 'Fuse'), ('Pathfinder', 'Pathfinder'), ('Rampart', 'Rampart'), ('Loba', 'Loba'), ('Crypto', 'Crypto'), ('Gibraltar', 'Gibraltar'), ('Bangalore', 'Bangalore'), ('Caustic', 'Caustic'), ('Lifeline', 'Lifeline')], max_length=60)),
                ('gp', models.PositiveIntegerField(default=0)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('tpt3', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
