# Generated by Django 2.2.5 on 2021-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApexLegendsStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='gp',
            field=models.PositiveIntegerField(default=0, verbose_name='Games Played'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kills',
            field=models.PositiveIntegerField(default=0, verbose_name='Kills'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='legend',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Bloodhound', 'Bloodhound'), ('Caustic', 'Caustic'), ('Crypto', 'Crypto'), ('Fuse', 'Fuse'), ('Gibraltar', 'Gibraltar'), ('Horizon', 'Horizon'), ('Lifeline', 'Lifeline'), ('Loba', 'Loba'), ('Mirage', 'Mirage'), ('Octane', 'Octane'), ('Pathfinder', 'Pathfinder'), ('Rampart', 'Rampart'), ('Revenant', 'Revenant'), ('Valkyrie', 'Valkyrie'), ('Wattson', 'Wattson'), ('Wraith', 'Wraith')], max_length=60, verbose_name='Legend'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tpt3',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Placed Top 3'),
        ),
    ]
