# Generated by Django 2.2.5 on 2020-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbooks',
            name='type',
            field=models.CharField(choices=[('Comics', 'Comics'), ('Graphic novels', 'Graphic novels')], max_length=60),
        ),
    ]
