# Generated by Django 2.2.5 on 2021-10-14 18:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('recipe', 'recipe'), ('tool', 'tool'), ('furniture', 'furniture'), ('wallpaper', 'wallpaper'), ('flooring', 'flooring'), ('art', 'art'), ('fossil', 'fossil'), ('fish', 'fish'), ('bugs', 'bugs')], max_length=60)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.CharField(blank=True, default='', max_length=20)),
            ],
            managers=[
                ('Items', django.db.models.manager.Manager()),
            ],
        ),
    ]
