# Generated by Django 2.2.5 on 2021-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Character', models.CharField(max_length=100)),
                ('First_Appearance', models.CharField(blank=True, default='', max_length=60)),
                ('Race_Type', models.CharField(blank=True, default='', max_length=60)),
                ('Affiliation', models.CharField(choices=[('light', 'light'), ('neutral', 'neutral'), ('dark', 'dark')], default='neutral', max_length=60)),
                ('Additional_Details', models.TextField(blank=True)),
            ],
        ),
    ]
