# Generated by Django 2.2.5 on 2021-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWarsUniverse', '0002_auto_20210622_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Affiliation',
            field=models.CharField(choices=[('light', 'light'), ('neutral', 'neutral'), ('dark', 'dark')], default='neutral', max_length=60),
        ),
    ]
